### PR TITLE
updated dependencies and tested build, it worked

### PR DESCRIPTION
**Pull request by aditya1rawat**

### CODE REVIEW

**Comment by aditya1rawat** [comment]
it's failing on linting for some reason

**Comment by rishiosaur** [comment]
@aditya1rawat can you run `yarn lint` and push?

**Review by rishiosaur — CHANGES_REQUESTED** [review]
The LICENSE.txt file shouldn't be there—we can include contribution & dependency graphs elsewhere.

**Review by rishiosaur — CHANGES_REQUESTED** [review]
@aditya1rawat lint & fix merge conflicts please

**Comment by aditya1rawat** [comment]
image
It says prop binding is not allowed apparently. How do you want me to fix it?

**Pull request closed without merging**
