### PR TITLE
Dependency Fixes & Image Optimization

### PR DESCRIPTION
**Pull request by aditya1rawat**

### CODE REVIEW

**Comment by rishiosaur** [comment]
@aditya1rawat can you delete `package-lock`?

**Comment by aditya1rawat** [comment]
done @rishiosaur

**Comment by rishiosaur** [comment]
@aditya1rawat can you update this with the newer code from `master`?

**Comment by aditya1rawat** [comment]
@rishiosaur I'm going to close this right now. I'm going to get yarn, then I'll update everything.

**Comment by rishiosaur** [comment]
Sounds good.

**Pull request closed without merging**
